name: flutter_slidable_max
description: Flutter 升级 3.35.7 之后，对 flutter_slidable 插件的升级（After Flutter upgrade 3.35.7, the upgrade of flutter_slidable plugins.）。
version: 4.1.1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  collection:

flutter:
